name: Auto Assign to Project

on:
  issues:
    types:
      - opened

permissions:
  issues: read
  pull-requests: read
  repository-projects: write

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.1
        with:
          project-url: https://github.com/orgs/mlabs-haskell/projects/37
          github-token: ${{ secrets.GITHUB_TOKEN }}
